# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Create and publish a Docker .NET image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

    buildDocker:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          run: |
            docker login -u treecmp -p kaims2017 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f ./src/TreeCmp.WebUI/Dockerfile -t treecmp/treecmp.webapp:latest
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/treecmp.webapp:latest